initial_run: '{{ env "INITIAL_RUN" | default "false" }}'
jobs:
  - id: ur-{{ .item.shisya }}-{{ .item.danchi }}
    schedule: "@every 10m"
    source:
      shell:
        command: ur {{ .item.shisya }} {{ .item.danchi }}
      filters:
        - template: |
            {{ range .source|json -}}
            {{   .name }}({{ .type }}): {{ .rent }}
            {{-  if .system }}(
            {{-    range $index, $s := .system }}
            {{-      if $index }}, {{end}}
            {{-      $s.制度名 }}
            {{-    end }})
            {{-  end -}}
            [共益費 {{ .commonfee }}{{ if .rent_normal }}, 通常 {{ .rent_normal }}{{ end }}]
            {{ end -}}
    label: "{{ .item.name }}"
    link: https://www.ur-net.go.jp/chintai/kanto/tokyo/{{ .item.shisya }}_{{ .item.danchi }}0.html
    actions:
      - slack:
          url: '{{ env "SLACK_WEBHOOK_URL" }}'
    with_items:
      - { shisya: 20, danchi: 688, name: "グリーンヒルズ東久留米" }
      - { shisya: 20, danchi: 399, name: "清瀬駅前ハイツ" }
      - { shisya: 20, danchi: 465, name: "グリーンプラザ高松＜光が丘＞" }
      - { shisya: 20, danchi: 391, name: "光が丘パークタウン いちょう通り八番街" }
      - { shisya: 20, danchi: 455, name: "光が丘パークタウン 大通り中央" }
      - { shisya: 20, danchi: 410, name: "光が丘パークタウン 四季の香弐番街" }
      - { shisya: 20, danchi: 369, name: "光が丘パークタウン 大通り南" }
      - { shisya: 20, danchi: 350, name: "光が丘パークタウン 公園南" }
      - { shisya: 20, danchi: 435, name: "光が丘パークタウン プロムナード十番街" }
  - id: amazon-{{ .item.id }}
    schedule: "@every 10m"
    label: '{{ .item.name }}'
    link: https://www.amazon.co.jp/dp/{{ .item.id }}/
    source:
      shell:
        command: |
          curl --compressed -sSL https://www.amazon.co.jp/dp/{{ .item.id }}/
      filters:
        - dom: '#priceblock_saleprice'
        - template: '{{ (.source|json).text }}'
      empty: fail
      retry: 3
    actions:
      - slack:
          url: '{{ env "SLACK_WEBHOOK_URL" }}'
    with_items:
      - { id: 'B07H56HB8T', name: 'TOPVISION プロジェクター' }
store:
  redis:
    redistogo: '{{ env "REDISTOGO_URL" }}'